def f():
    raise Exception('This is the exception message')

f()
